version: "3"
services:
  admin:
    image: fetebot-release
    container_name: fetebot-admin
    env_file:
      - .env.deploy
    environment:
      - APP_MODE=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: eval FeteBot.Release.migrate
    restart: "no"
  server:
    image: fetebot-release
    container_name: fetebot-bot
    env_file:
      - .env.deploy
    environment:
      - APP_MODE=bot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: start
    depends_on:
      - admin
    restart: unless-stopped
