# fly.toml app configuration file generated for fete-bot on 2023-11-21T20:25:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fete-bot"
primary_region = "yul"

[build]

[deploy]
  release_command = "/app/bin/migrate"
