# ex: sw=2
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fete-bot"
primary_region = "yul"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/"
